# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

BOX_IMAGE = "centos/stream8"
NETWORK = "public_network"

Vagrant.configure("2") do |config|

  # Create a master VM before creating the linked clones
  # By default new machines are created by importing the base box. 
  # For large boxes this produces a large overhead in terms of time 
  # (the import operation) and space (the new machine contains a copy of 
  # the base box’s image). 
  # Using linked clones can drastically reduce this overhead.
  # Linked clones are based on a master VM, which is generated by importing 
  # the base box only once the first time it is required. For the linked clones 
  # only differencing disk images are created where the parent disk image 
  # belongs to the master VM.
  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
  end

  config.vm.define "server" do |server|
    server.vm.box = BOX_IMAGE
    server.vm.hostname = "zabbix-server"
    server.vm.network NETWORK
    server.vm.provision :shell, path: "provision-server.sh"
    server.vm.provision :shell, path: "bootstrap-server.sh", run: 'always'
  end

  config.vm.define "proxy" do |proxy|
    proxy.vm.box = BOX_IMAGE
    proxy.vm.hostname = "zabbix-proxy"
    proxy.vm.network NETWORK
  end

  config.vm.define "host" do |host|
    host.vm.box = BOX_IMAGE
    host.vm.hostname = "zabbix-host"
    host.vm.network NETWORK
  end
  
  config.vm.provision :shell, path: "provision.sh"
  config.vm.provision :shell, path: "bootstrap.sh", run: 'always'

end
